version: '3.9'

services:
    api:
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
          - 8001:8000
        volumes:
          - ./api:/api
        tty: true
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5

    bot:
        command: sh -c "python3 main.py"
        build:
            context: ./bot
            dockerfile: Dockerfile
        volumes:
          - ./bot:/bot
        tty: true
        stdin_open: true
        networks:
            vpcbr:
                ipv4_address: 10.5.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1